//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporationDepartments.UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentBudgets
    {
        public int DepartmentBudgetID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public Nullable<System.DateTime> LastReviewDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
