//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporationDepartments.UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompensation
    {
        public int EmployeeCompensationID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> LastSalaryReviewDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
